# Generated by Django 6.0.3 on 2026-04-16 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("id_paciente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("diagnostico", models.TextField(blank=True, null=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pacientes",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=150, null=True)),
                ("id_rol", models.IntegerField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
        migrations.CreateModel(
            name="PlanCuidado",
            fields=[
                ("id_plan", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "id_paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "planes_cuidado",
            },
        ),
        migrations.CreateModel(
            name="ActividadCuidado",
            fields=[
                ("id_actividad", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_actividad", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("hora_programada", models.TimeField()),
                ("frecuencia", models.CharField(blank=True, max_length=50, null=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "id_plan",
                    models.ForeignKey(
                        db_column="id_plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.plancuidado",
                    ),
                ),
            ],
            options={
                "db_table": "actividades_cuidado",
            },
        ),
        migrations.CreateModel(
            name="RecuperacionPassword",
            fields=[
                (
                    "id_recuperacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("codigo_recuperacion", models.CharField(max_length=255)),
                ("fecha_expiracion", models.DateTimeField()),
                ("utilizado", models.BooleanField(default=False)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "recuperacion_contraseña",
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="id_cuidador",
            field=models.ForeignKey(
                db_column="id_cuidador",
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.usuario",
            ),
        ),
        migrations.CreateModel(
            name="RegistroDiario",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("realizada", models.BooleanField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("hora_registro", models.TimeField(blank=True, null=True)),
                (
                    "id_actividad",
                    models.ForeignKey(
                        db_column="id_actividad",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.actividadcuidado",
                    ),
                ),
            ],
            options={
                "db_table": "registro_diario",
                "unique_together": {("id_actividad", "fecha")},
            },
        ),
    ]
