# Generated by Django 6.0.3 on 2026-03-13 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="id",
        ),
        migrations.AddField(
            model_name="usuario",
            name="id_usuario",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="correo",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterModelTable(
            name="usuario",
            table="usuarios",
        ),
        migrations.CreateModel(
            name="RecuperacionPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6)),
                ("fecha_expiracion", models.DateTimeField()),
                ("usado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "recuperacion_contraseña",
            },
        ),
    ]
