# Generated by Django 6.0.3 on 2026-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actividadcuidado",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="actividadcuidado",
            name="estado",
        ),
        migrations.AddField(
            model_name="actividadcuidado",
            name="tipo",
            field=models.CharField(default="otro", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actividadcuidado",
            name="frecuencia",
            field=models.CharField(default="diaria", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actividadcuidado",
            name="nombre_actividad",
            field=models.CharField(max_length=100),
        ),
    ]
