# Generated by Django 6.0.3 on 2026-03-17 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_usuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recuperacionpassword',
            old_name='usado',
            new_name='utilizado',
        ),
        migrations.RemoveField(
            model_name='recuperacionpassword',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='recuperacionpassword',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recuperacionpassword',
            name='usuario',
        ),
        migrations.AddField(
            model_name='recuperacionpassword',
            name='codigo_recuperacion',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recuperacionpassword',
            name='id_recuperacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='recuperacionpassword',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_rol',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
