# Generated by Django 6.0.3 on 2026-05-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_notificacion'),
        ('usuarios', '0002_remove_actividadcuidado_descripcion_and_more'),
    ]

    operations = [
    ]
