# Generated by Django 6.0.3 on 2026-05-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_merge_20260517_1942"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamiliarPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_familiar",
                    models.ForeignKey(
                        db_column="id_familiar",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes_asignados",
                        to="usuarios.usuario",
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familiares_asignados",
                        to="usuarios.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "familiar_paciente",
                "unique_together": {("id_familiar", "id_paciente")},
            },
        ),
    ]
