# Generated by Django 6.0.3 on 2026-04-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_rename_usado_recuperacionpassword_utilizado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("id_paciente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("diagnostico", models.TextField(blank=True, null=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "id_cuidador",
                    models.ForeignKey(
                        db_column="id_cuidador",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "pacientes",
            },
        ),
        migrations.CreateModel(
            name="PlanCuidado",
            fields=[
                ("id_plan", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "id_paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "planes_cuidado",
            },
        ),
    ]
