# Generated by Django 6.0.3 on 2026-05-20 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_familiarpaciente"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialModificacion",
            fields=[
                ("id_historial", models.AutoField(primary_key=True, serialize=False)),
                ("campo_modificado", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField()),
                ("fecha_modificacion", models.DateTimeField(auto_now_add=True)),
                (
                    "id_plan",
                    models.ForeignKey(
                        db_column="id_plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.plancuidado",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "historial_modificaciones",
            },
        ),
    ]
