# Generated by Django 6.0.3 on 2026-04-14 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_paciente_plancuidado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadCuidado",
            fields=[
                ("id_actividad", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_actividad", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("hora_programada", models.TimeField()),
                ("frecuencia", models.CharField(max_length=50)),
                (
                    "id_plan",
                    models.ForeignKey(
                        db_column="id_plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.plancuidado",
                    ),
                ),
            ],
            options={
                "db_table": "actividades_cuidado",
            },
        ),
        migrations.CreateModel(
            name="RegistroDiario",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("realizada", models.BooleanField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("hora_registro", models.TimeField(blank=True, null=True)),
                (
                    "id_actividad",
                    models.ForeignKey(
                        db_column="id_actividad",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.actividadcuidado",
                    ),
                ),
            ],
            options={
                "db_table": "registro_diario",
                "unique_together": {("id_actividad", "fecha")},
            },
        ),
    ]
